### PR TITLE
Update add.2o7Net hosts

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by FadeMind** [comment]
Hello

Thanks for PR. 

`omtrdc.net` is whitelisted in AdguardTeam/AdGuardSDNSFilter > `https://raw.githubusercontent.com/AdguardTeam/AdGuardSDNSFilter/master/Filters/exclusions.txt`

Please remove them from PR. 

CC @StevenBlack  @sjhgvr

I see mix other domains than 2o7Net variants here.

**Comment by sjhgvr** [comment]
> @sjhgvr
What's my todo in this?

**Comment by FadeMind** [comment]
@sjhgvr I see here a lot of domains, some are from 2o7 network, others nope. Please review if you will have a moment. I don't want merge it before sure that domains don't crack anything ;)

**Comment by sjhgvr** [comment]
> @sjhgvr I see here a lot of domains, some are from 2o7 network, others nope. Please review if you will have a moment. I don't want merge it before sure that domains don't crack anything ;)

Ah k. Well I rely on my awesome automated script to sort that out for me. And if issues arise, I'll fix them accordingly.

**Comment by smed79** [comment]
> Please remove `omtrdc.net`

removed https://github.com/FadeMind/hosts.extras/pull/55/commits/d5863bca655602985642c4465b16fa318075a58a

> I see mix other domains than 2o7Net

Some 2o7Net customers use a custom domain instead of `*.2o7.net`

> I don't want merge it before sure that domains don't crack anything

I can remove them if you are not comfortable with these variants.

@FadeMind

**Comment by FadeMind** [comment]
@smed79 I will wait for @sjhgvr and @StevenBlack  reply for his statement. I very much appreciate your work here. Thank you.  

Regards

**Comment by FadeMind** [comment]
@smed79 OK, merging. If false positives show ups, I will care of it. 

I very much appreciate your work. Thank you.

**Pull request merged**
