### PR TITLE
update antipopads-re hosts

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by FadeMind** [comment]
@smed79 check mailbox 😉

**Comment by FadeMind** [comment]
@smed79 see https://github.com/FadeMind/hosts.extras/blob/master/antipopads-re/update.json#L6

I created only templates for StevenBlack hosts project compatible. If user download template and add it to proper dir, hosts  will be updated from originals.

**Comment by FadeMind** [comment]
I noticed this in readme also.

**Comment by smed79** [comment]
> check mailbox

Check & accepted. Thank you for your trust.

> If user download template and add it to proper dir, hosts will be updated from originals.

Ok, thanks for the explanation.

**Comment by FadeMind** [comment]
@smed79 exceptions have MIRRORED notice in readme.md

**Pull request merged**
